---
title: "Reticulate Example"
author: "Caden Hewlett"
date: "`r Sys.Date()`"
header-includes:
   - \usepackage{bbm}
   - \usepackage{upgreek}
   - \usepackage{booktabs}
output: pdf_document
---

```{r setup, include=FALSE}
library(extraDistr)
library(ggplot2)
library(pracma)
library(distr)
library(latex2exp)
library(knitr)
library(rstan)
library(reticulate)
require(dplyr, quietly = TRUE)
require(rstan, quietly = TRUE)
require(knitr, quietly = TRUE)
```

Example of using Python and `reticulate`, as well as `py2tex` to convert the output to natural latex.
```{python, results = FALSE}
from sympy import symbols, simplify
from pytexit import py2tex

# Define symbols
a = symbols('a')

# Original equation's rearrangement
left_side_coefficient = 1 - (1/(6*a))
right_side = (3 - 2*a) / (6*a)

# Simplify the equation for p(1)
rho_1 = simplify(right_side / left_side_coefficient)
# sympy.latex(eval(rho_1))
pytex_obj = py2tex(str(rho_1))
```
Then, in the `R` cell, by setting `results = 'asis'`, we render the equation directly. 
```{r, results='asis'}
cat(py$pytex_obj)
```


```{python}
from sympy import symbols, solve, lambdify, diff

b0, b1, b2, x = symbols('b_0 b_1 b_2 x')

model_eq = b0 + b1*x + b2*x**2

roots = solve(model_eq, x)

root_funcs = [lambdify((b0, b1, b2), root) for root in roots]

## x-value where y = 0
b0_val, b1_val, b2_val = (1, 0.0102, -4.321e-5)
root_values = [root_func(b0_val, b1_val, b2_val) for root_func in root_funcs]
print([root for root in root_values if root > 0])


## x-value where d/dx (y) = 0
y_prime = diff(model_eq, x)
## set to zero
extrema = solve(y_prime, x)
## transform to function
zeroes = lambdify((b1, b2), extrema)
print(zeroes(b1_val, b2_val))
```

$$
\begin{aligned}
f(x, h_i, y_i) &=  f(x)f(h_i \mid x)f(y_i \mid h_i) &\text{Chain Rule}\\
L\Big(f\big(x, \{h_i\}_{i=1}^n, \{y_i\}_{i=1}^n\big)\Big) &= \prod_{i = 1}^n \bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg) &\text{Definition of Likelihood} \\
\gamma(x) &= \sum_{y_{n-1} = 0}^{\infty} \sum_{y_{n} = 0}^{\infty}  \bigg(\prod_{i = 1}^n \bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg)\bigg) &\text{R.B. First Step} \\
\gamma(x) &= \prod_{i = 1}^{n-2} \bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg) \sum_{h_{n-1} = 0}^{\infty} \sum_{h_{n} = 0}^{\infty} \bigg(\prod_{i \in \{n-1, \;n \}} \bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg)\bigg)  &\text{Separate Uncensored} \\
\gamma(x) &= \prod_{i = 1}^{n-2} \bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg)  \bigg(\prod_{i =(n-1)}^n \sum_{h_i = 0}^{\infty}\bigg( f(x)f(h_i \mid x)f(y_i \mid h_i)\bigg)\bigg)  &\text{Move the Sum} \\
\gamma(x) &= f(x)\prod_{i = 1}^{n-2} \bigg( f(h_i \mid x)\big(h_i(1-\mathbb{1}[h_i \geq 8])\big)\bigg)  \bigg(\prod_{i =(n-1)}^n \sum_{h_i = 0}^{\infty}\bigg( f(h_i \mid x)\big(L\cdot\mathbb{1}[h_i \geq 8])\bigg)\bigg)  &\text{Plug in Indicator} \\
\gamma(x) &= \underbrace{f(x)}_{\text{Prior}}\underbrace{\prod_{i = 1}^{n-2} \bigg( f(h_i \mid x)\bigg)}_{\text{Likelihood as Usual}}  \underbrace{\bigg(\prod_{i =(n-1)}^n \sum_{h_i = L}^{\infty}\Big( f(h_i \mid x) \bigg)}_{\text{Likelihood for } \geq \,L}  & \star \;\text{Messed up notation at some point.} \\
\gamma(x) &= p_{\text{exp}}(x ; \lambda)\prod_{i = 1}^{n-2} p_{\text{pois}}(h_i ; x)\prod_{n-1}^{n}\Big( \mathbb{P}\big(\text{pois}(x) \geq L\,\big) \Big)&\;\text{Starting to simplify} \\
\gamma(x) &= p_{\text{exp}}(x ; \lambda)\prod_{i = 1}^{n-2} p_{\text{pois}}(h_i ; x)\prod_{n-1}^{n}\big(1 - F_{\text{pois}}(L;x)\big)&\;\text{Done?} \\
\gamma(x) &= p_{\text{exp}}(x ; 1/100)\prod_{i =1}^{18} p_{\text{pois}}(h_i ; x)\prod_{i = 19}^{20}\big(1 - F_{\text{pois}}(8;x)\big)&\;\text{+ Problem Context} 
\end{aligned}
$$
Or, more formally, $$\lim_{M \rightarrow \infty}\bigg( \mathbb{P}\Big( \dfrac{\sqrt{M}(\bar{X}_{\text{m}} - \mu)}{\sigma_a} \leq z\Big)\bigg) = \Phi(z)$$

So then from this, a $$95\%$$ C.I. can be constructed: 
$$\begin{aligned}
\text{CI}(0.95) &:= \bigg(Z_{0.025} \leq \dfrac{\sqrt{M}(\bar{X}_{\text{m}} - \mu)}{\sigma_a} \leq Z_{0.975}\bigg) \\
\text{CI}(0.95) &:= \bigg(Z_{0.025}\Big(\dfrac{\sigma_a}{\sqrt{M}} \Big) \leq (\bar{X}_{\text{m}} - \mu) \leq Z_{0.975}\Big(\dfrac{\sigma_a}{\sqrt{M}} \Big)\bigg) \\
\text{CI}(0.95) &:= \bigg(\bar{X}_{\text{m}} + Z_{0.025}\Big(\dfrac{\sigma_a}{\sqrt{M}}\Big) \leq   \mu \leq \bar{X}_{\text{m}} + Z_{0.975}\Big(\dfrac{\sigma_a}{\sqrt{M}} \Big)\bigg)
\end{aligned}$$